version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command:
      - "uvicorn"
      - "tree_api.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"