apiVersion: v1
kind: Service
metadata:
  name: treeapi-service
  namespace: treeapi-project
  labels:
    app: treeapi-app
spec:
  selector:
    app: treeapi-app
  ports:
    - port: 8000
      targetPort: 8000