name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  
    runs-on: ububuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Test the code
      run: make test
    

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tree-api:$(date +%s)
